#################################################################
###################### Hexo Configuration #######################
#################################################################

# Site
title: Martin's Blog
subtitle: never give up
description: 越努力，越幸运
keywords: "Android"
language: zh-CN
timezone: "Asia/Shanghai"
author: Martin Chen

# URL
url: http://www.android8527.com
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - robots.txt
  - animate/*
  - highlight/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true

relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''

# Home page setting
index_generator:
  per_page: 4
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 5
pagination_dir: page

# Extensions
theme: next

archive_generator:
  per_page: 12
  yearly: true
  monthly: true
  daily: false

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  lazyload: true
  prependRoot: true
  postAsset: true

search:
#  path: search.json
#  field: all
  path: search.xml
  field: post
  content: true
  format: html

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 2
  wpm: 300
  suffix: "mins."

pace:
  enable: true

canvas_ribbon:
  enable: true
  size: 300
  alpha: 0.6
  zIndex: -1

deploy:
  type: git
  repo: https://github.com/android9527/android9527.github.io.git
  branch: master
#  message: [message]